apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: house-home-assistant-ingress
  labels:
    component: house-home-assistant
spec:
  ingressClassName: public
  rules:
  - host: ha.home.seifts.us
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: house-home-assistant-service
            port:
              number: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: house-home-assistant-service
  labels:
    component: house-home-assistant
spec:
  ports:
  - protocol: TCP
    port: 8123
    targetPort: 8123
  selector:
    component: house-home-assistant
  type: ClusterIP
