apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: house-home-assistant-ingress
  labels:
    component: house-home-assistant
spec:
  ingressClassName: public
  rules:
  - host: ha.home.seifts.us
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: house-home-assistant-service
            port:
              number: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: house-home-assistant-service
  labels:
    component: house-home-assistant
spec:
  ports:
  - protocol: TCP
    port: 8123
    targetPort: 8123
  selector:
    component: house-home-assistant
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-home-assistant-deployment
  labels:
    component: house-home-assistant
spec:
  selector:
    matchLabels:
      component: house-home-assistant
  replicas: 1
  template:
    metadata:
      labels:
        component: house-home-assistant
    spec:
      containers:
        - name: house-home-assistant-image
          image: ghcr.io/home-assistant/home-assistant:2024.2
          ports:
            - containerPort: 8123
          envFrom:
            - configMapRef:
                name: "house-home-assistant-config"
          volumeMounts:
            - name: house-home-assistant-config-storage
              mountPath: /config
      volumes:
        - name: house-home-assistant-config-storage
          nfs:
            server: mbp.home.seifts.us
            path: /srv/k8s-home-assistant
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: house-home-assistant-pvc
  labels:
    component: house-home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
