apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: house-home-assistant
resources:
 - namespace.yaml
 - house-home-assistant.yaml
configMapGenerator:
  - name: house-home-assistant-config
    literals:
      - TZ="America/New_York"
